apiVersion: v1
kind: ServiceAccount
metadata:
  name: tester
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tester-auth-delegator
  labels:
    app: vault
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: tester
  namespace: default